### ISSUE TITLE
请问64位win10，版本：1803怎么启动VPN，托盘能打开chromium，但点击启动VPN无任何反应

### ISSUE THREAD

**Issue by i04lovemusic** [jjqqkk/chromium#142]
请问64位win10，版本：1803怎么启动VPN，托盘能打开chromium，但点击启动VPN无任何反应

**Comment by amber06** [comment]
请问你打开chromium会显示崩溃吗

**Comment by i04lovemusic** [comment]
> 请问你打开chromium会显示崩溃吗

并不会，chromium没问题，唯有全局VPN没反应

**Comment by amber06** [comment]
你好，我是从jjqqkk打开的 一直显示崩溃 从网页下载的安装包打开也是显示崩溃




------------------ 原始邮件 ------------------
发件人: "i04lovemusic"<notifications@github.com>; 
发送时间: 2019年6月14日(星期五) 上午9:37
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 
抄送: "AAM"<782362133@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jjqqkk/chromium] 请问64位win10，版本：1803怎么启动VPN，托盘能打开chromium，但点击启动VPN无任何反应 (#142)



 
请问你打开chromium会显示崩溃吗
  
并不会，chromium没问题，唯有全局VPN没反应

**Comment by amber06** [comment]
你是从jjqqkk打开的还是从下载的安装包呢

**Comment by i04lovemusic** [comment]
> 你好，我是从jjqqkk打开的 一直显示崩溃 从网页下载的安装包打开也是显示崩溃
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "i04lovemusic"<notifications@github.com>; 发送时间: 2019年6月14日(星期五) 上午9:37 收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 抄送: "AAM"<782362133@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [jjqqkk/chromium] 请问64位win10，版本：1803怎么启动VPN，托盘能打开chromium，但点击启动VPN无任何反应 (#142) 请问你打开chromium会显示崩溃吗 并不会，chromium没问题，唯有全局VPN没反应 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我也是从jjqqkk打开chromium，使用正常，我的系统是从MSDN里下载的，某宝买的激活钥匙，提到这点是因为我曾使用网上的盗版系统，各种问题，后来索性到MSDN下载系统。至于您的情况是否由于系统造成我也不得而知，因为我也是菜鸟，对电脑不太熟悉，抱歉

**Comment by amber06** [comment]
好的谢谢你 




------------------ 原始邮件 ------------------
发件人: "i04lovemusic"<notifications@github.com>; 
发送时间: 2019年6月14日(星期五) 上午9:51
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 
抄送: "AAM"<782362133@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jjqqkk/chromium] 请问64位win10，版本：1803怎么启动VPN，托盘能打开chromium，但点击启动VPN无任何反应 (#142)



 
你好，我是从jjqqkk打开的 一直显示崩溃 从网页下载的安装包打开也是显示崩溃
 …
 ------------------ 原始邮件 ------------------ 发件人: "i04lovemusic"notifications@github.com; 发送时间: 2019年6月14日(星期五) 上午9:37 收件人: "jjqqkk/chromium"chromium@noreply.github.com; 抄送: "AAM"782362133@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [jjqqkk/chromium] 请问64位win10，版本：1803怎么启动VPN，托盘能打开chromium，但点击启动VPN无任何反应 (#142) 请问你打开chromium会显示崩溃吗 并不会，chromium没问题，唯有全局VPN没反应 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
我也是从jjqqkk打开chromium，使用正常，我的系统是从MSDN里下载的，某宝买的激活钥匙，提到这点是因为我曾使用网上的盗版系统，各种问题，后来索性到MSDN下载系统。至于您的情况是否由于系统造成我也不得而知，因为我也是菜鸟，对电脑不太熟悉，抱歉

**Comment by i04lovemusic** [comment]
我用64位WIN7系统的电脑启动全局VPN和chromium均正常，win10无论是关闭防火墙、win7兼容模式，管理员运行都启动不了全局VPN，但chromium正常

**Comment by tytme** [comment]
win7 64位  右键点击JJQQKK点启动VPN和Android vpn无反应，   点击Chromium  可以正常打开网页.望解决！
